apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque

stringData:
  ENV: "production"

  POSTGRES_DB: "myauthapp_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "REPLACE_ME"

  DATABASE_URL: "postgresql://postgres:REPLACE_ME@postgres:5432/myauthapp_db"

  REDIS_URL: "redis://redis:6379"

  JWT_PRIVATE_KEY_PATH: "/app/keys/private.pem"
  JWT_PUBLIC_KEY_PATH: "/app/keys/public.pem"

  OTEL_EXPORTER_ENDPOINT: "http://otel-collector:4317"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "REPLACE_ME"

  GOOGLE_CLIENT_ID: "REPLACE_ME"
  GOOGLE_CLIENT_SECRET: "REPLACE_ME"

  AUTH_GITHUB_CLIENT_ID: "REPLACE_ME"
  AUTH_GITHUB_CLIENT_SECRET: "REPLACE_ME"

  TWILIO_ACCOUNT_SID: "REPLACE_ME"
  TWILIO_AUTH_TOKEN: "REPLACE_ME"
  TWILIO_PHONE_NUMBER: "REPLACE_ME"