"""update meta_info column in  audit logs table

Revision ID: 212146f0bc85
Revises: fc2d1b79e1d0
Create Date: 2026-03-03 15:50:41.940237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212146f0bc85'
down_revision: Union[str, Sequence[str], None] = 'fc2d1b79e1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
