"""add token version to user

Revision ID: 5b4d33c386ea
Revises: 8847346d50db
Create Date: 2026-03-03 10:39:09.361800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4d33c386ea'
down_revision: Union[str, Sequence[str], None] = '8847346d50db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), nullable=True, server_default="0")
    )

    # Step 2: Remove default (optional but recommended)
    op.alter_column('users', 'token_version', server_default=None)

    # Step 3: Enforce NOT NULL
    op.alter_column('users', 'token_version', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
