"""update column in  password_reset_token model

Revision ID: 958d4e0f79f4
Revises: c47c65303f1d
Create Date: 2026-03-06 10:54:57.888934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958d4e0f79f4'
down_revision: Union[str, Sequence[str], None] = 'c47c65303f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'password_reset_tokens', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
