"""update oauth_account model

Revision ID: e547afac982b
Revises: 12955f1e90dc
Create Date: 2026-03-11 12:40:57.999419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e547afac982b'
down_revision: Union[str, Sequence[str], None] = '12955f1e90dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_user', 'oauth_accounts', type_='unique')
    # ### end Alembic commands ###
